// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RedWolf.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for GrawlTaskingStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GrawlTaskingStatus
    {
        [EnumMember(Value = "Uninitialized")]
        Uninitialized,
        [EnumMember(Value = "Tasked")]
        Tasked,
        [EnumMember(Value = "Progressed")]
        Progressed,
        [EnumMember(Value = "Completed")]
        Completed,
        [EnumMember(Value = "Aborted")]
        Aborted
    }
    internal static class GrawlTaskingStatusEnumExtension
    {
        internal static string ToSerializedValue(this GrawlTaskingStatus? value)
        {
            return value == null ? null : ((GrawlTaskingStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this GrawlTaskingStatus value)
        {
            switch( value )
            {
                case GrawlTaskingStatus.Uninitialized:
                    return "Uninitialized";
                case GrawlTaskingStatus.Tasked:
                    return "Tasked";
                case GrawlTaskingStatus.Progressed:
                    return "Progressed";
                case GrawlTaskingStatus.Completed:
                    return "Completed";
                case GrawlTaskingStatus.Aborted:
                    return "Aborted";
            }
            return null;
        }

        internal static GrawlTaskingStatus? ParseGrawlTaskingStatus(this string value)
        {
            switch( value )
            {
                case "Uninitialized":
                    return GrawlTaskingStatus.Uninitialized;
                case "Tasked":
                    return GrawlTaskingStatus.Tasked;
                case "Progressed":
                    return GrawlTaskingStatus.Progressed;
                case "Completed":
                    return GrawlTaskingStatus.Completed;
                case "Aborted":
                    return GrawlTaskingStatus.Aborted;
            }
            return null;
        }
    }
}
