// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RedWolf.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for GrawlStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GrawlStatus
    {
        [EnumMember(Value = "Uninitialized")]
        Uninitialized,
        [EnumMember(Value = "Stage0")]
        Stage0,
        [EnumMember(Value = "Stage1")]
        Stage1,
        [EnumMember(Value = "Stage2")]
        Stage2,
        [EnumMember(Value = "Active")]
        Active,
        [EnumMember(Value = "Lost")]
        Lost,
        [EnumMember(Value = "Exited")]
        Exited,
        [EnumMember(Value = "Disconnected")]
        Disconnected,
        [EnumMember(Value = "Hidden")]
        Hidden
    }
    internal static class GrawlStatusEnumExtension
    {
        internal static string ToSerializedValue(this GrawlStatus? value)
        {
            return value == null ? null : ((GrawlStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this GrawlStatus value)
        {
            switch( value )
            {
                case GrawlStatus.Uninitialized:
                    return "Uninitialized";
                case GrawlStatus.Stage0:
                    return "Stage0";
                case GrawlStatus.Stage1:
                    return "Stage1";
                case GrawlStatus.Stage2:
                    return "Stage2";
                case GrawlStatus.Active:
                    return "Active";
                case GrawlStatus.Lost:
                    return "Lost";
                case GrawlStatus.Exited:
                    return "Exited";
                case GrawlStatus.Disconnected:
                    return "Disconnected";
                case GrawlStatus.Hidden:
                    return "Hidden";
            }
            return null;
        }

        internal static GrawlStatus? ParseGrawlStatus(this string value)
        {
            switch( value )
            {
                case "Uninitialized":
                    return GrawlStatus.Uninitialized;
                case "Stage0":
                    return GrawlStatus.Stage0;
                case "Stage1":
                    return GrawlStatus.Stage1;
                case "Stage2":
                    return GrawlStatus.Stage2;
                case "Active":
                    return GrawlStatus.Active;
                case "Lost":
                    return GrawlStatus.Lost;
                case "Exited":
                    return GrawlStatus.Exited;
                case "Disconnected":
                    return GrawlStatus.Disconnected;
                case "Hidden":
                    return GrawlStatus.Hidden;
            }
            return null;
        }
    }
}
