// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RedWolf.API.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GrawlCommand
    {
        /// <summary>
        /// Initializes a new instance of the GrawlCommand class.
        /// </summary>
        public GrawlCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GrawlCommand class.
        /// </summary>
        public GrawlCommand(string command, System.DateTime commandTime, int commandOutputId, string userId, int? id = default(int?), CommandOutput commandOutput = default(CommandOutput), RedWolfUser user = default(RedWolfUser), int? grawlTaskingId = default(int?), GrawlTasking grawlTasking = default(GrawlTasking), int? grawlId = default(int?))
        {
            Id = id;
            Command = command;
            CommandTime = commandTime;
            CommandOutputId = commandOutputId;
            CommandOutput = commandOutput;
            UserId = userId;
            User = user;
            GrawlTaskingId = grawlTaskingId;
            GrawlTasking = grawlTasking;
            GrawlId = grawlId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "command")]
        public string Command { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commandTime")]
        public System.DateTime CommandTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commandOutputId")]
        public int CommandOutputId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commandOutput")]
        public CommandOutput CommandOutput { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public RedWolfUser User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grawlTaskingId")]
        public int? GrawlTaskingId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grawlTasking")]
        public GrawlTasking GrawlTasking { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grawlId")]
        public int? GrawlId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Command == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Command");
            }
            if (UserId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UserId");
            }
            if (CommandOutput != null)
            {
                CommandOutput.Validate();
            }
            if (User != null)
            {
                User.Validate();
            }
            if (GrawlTasking != null)
            {
                GrawlTasking.Validate();
            }
        }
    }
}
